### ISSUE TITLE
When using this with react-leaflet-v4 the markers "flicker"

### ISSUE THREAD

**Issue by Joyfulasteroid** [TurtIeSocks/react-leaflet-supercluster#4]
Used this as per the example provided and noticed that the markers rendered as normal and the clustering was very performant. However, with custom markers set (using my own png images and the Icon from leaflet) the markers will only be visible for a second before disappearing. They will reappear a second later then again disappear.

**Comment by TurtIeSocks** [comment]
Thanks for the report! Can you provide a small example code block of your icon, so I can verify?

In general, this library needs a lot of work to be production ready, hopefully some time frees up soon so I can continue with it, thanks for giving it a try though!

**Comment by Joyfulasteroid** [comment]
Thanks for the response to the Issue,

I have abandoned the project I was working on due to react-leaflet not having the ability to load 20k + markers in any kind of performant way. Your supercluster port was probably the best in terms of render performance however due to the issues with the icons I can't use it and so have decided to leave my website using vanillaJS to render the leaflet map with the 20k markers rather than continuing with a react re-code

**Comment by TurtIeSocks** [comment]
That's fair. Despite writing these adapter libraries, I'm not very convinced that Leaflet and React mix very well. They're kind of at odds with each other with how they work. For that many markers, have you looked into using PIXI?
